export interface InstagramPost {
  url: string;
  category: string;
}

// Unique Karigrah Instagram post/reel permalinks, sourced from the account's own
// post export and categorized by keyword analysis of each caption.
export const INSTAGRAM_POSTS: InstagramPost[] = [
  { url: 'https://www.instagram.com/p/DZo5lftSB-I/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DaXEAUHIlWz/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DcOhHHoI5xd/', category: 'Kitchen' },
  { url: 'https://www.instagram.com/p/DZK4HXdGL9O/', category: 'Wardrobe & Storage' },
  { url: 'https://www.instagram.com/p/DbaG4Trya_3/', category: 'Office & Commercial' },
  { url: 'https://www.instagram.com/p/DaNbk8TSGpM/', category: 'Office & Commercial' },
  { url: 'https://www.instagram.com/p/DbgLv8lpXSp/', category: 'Bedroom' },
  { url: 'https://www.instagram.com/p/DYueOqRyUcE/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DbGI44mSBIX/', category: 'Wardrobe & Storage' },
  { url: 'https://www.instagram.com/p/DX6xWnspUJp/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DYjvAWbp0ug/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DX1dd46oTk-/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DcDkmOByUdG/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DYUwfDQJ_a7/', category: 'Office & Commercial' },
  { url: 'https://www.instagram.com/p/DZZgCaBIGuE/', category: 'Testimonials' },
  { url: 'https://www.instagram.com/p/DXWAEYFEou1/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DXO7WoCEoEx/', category: 'Office & Commercial' },
  { url: 'https://www.instagram.com/p/DZureluSfyB/', category: 'Kitchen' },
  { url: 'https://www.instagram.com/p/DYebjgVojzg/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DbQsjt8oqGk/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/Db55W4YyYwJ/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DZEp_tnINRM/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DaageaWI6Ab/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DXcHpqZCVQT/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DVm8zYKgRzP/', category: 'Festive & Occasions' },
  { url: 'https://www.instagram.com/p/DWnt2aMCaCj/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DWs8r-_Et5D/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DWbN8IKiULu/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DWQqZfRAfyg/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DWV2glPiJfN/', category: 'Renovation' },
  { url: 'https://www.instagram.com/p/DW3IGHbkgh8/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DXHU2NlCEyl/', category: 'Office & Commercial' },
  { url: 'https://www.instagram.com/p/DWl8kREiRdK/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DVn-r5SgeTq/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DT9kqiZiDnX/', category: 'Festive & Occasions' },
  { url: 'https://www.instagram.com/p/DUFbSaDCLy1/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DUdgGaCD_3k/', category: 'Home Bar' },
  { url: 'https://www.instagram.com/p/DU8ToO_AY01/', category: 'Renovation' },
  { url: 'https://www.instagram.com/p/DUYO9hMgQwW/', category: 'Renovation' },
  { url: 'https://www.instagram.com/p/DWeGGheiVve/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DT159R2ESfX/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DUxY9bhEZDL/', category: 'Festive & Occasions' },
  { url: 'https://www.instagram.com/p/DTzXkO0gVmN/', category: 'Kitchen' },
  { url: 'https://www.instagram.com/p/DTcN_1PAasf/', category: 'Festive & Occasions' },
  { url: 'https://www.instagram.com/p/DUAFb8fgWul/', category: 'Wardrobe & Storage' },
  { url: 'https://www.instagram.com/p/DW88zArEidH/', category: 'Studio & Behind the Scenes' },
  { url: 'https://www.instagram.com/p/DTfPN-mCB12/', category: 'Festive & Occasions' },
  { url: 'https://www.instagram.com/p/DTSoOTMCJa-/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DUpcHEHiEcA/', category: 'Renovation' },
  { url: 'https://www.instagram.com/p/DSP7q7WgVxJ/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DTIoJlfCMi_/', category: 'Office & Commercial' },
  { url: 'https://www.instagram.com/p/DSaTNvtgQQ9/', category: 'Renovation' },
  { url: 'https://www.instagram.com/p/DTQDR8ViI0U/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DTp0M_ugZh9/', category: 'Studio & Behind the Scenes' },
  { url: 'https://www.instagram.com/p/DTDW8ZdgUXA/', category: 'Wardrobe & Storage' },
  { url: 'https://www.instagram.com/p/DR9xp0SgRdO/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DU3XPMvAXNV/', category: 'Renovation' },
  { url: 'https://www.instagram.com/p/DUDptX2iCLx/', category: 'Office & Commercial' },
  { url: 'https://www.instagram.com/p/DSpmiIdgbIu/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DRkRmj3gUWn/', category: 'Studio & Behind the Scenes' },
  { url: 'https://www.instagram.com/p/DS5M5cOAdM4/', category: 'Studio & Behind the Scenes' },
  { url: 'https://www.instagram.com/p/DQhXEPNiHLT/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DQb9s1niJAg/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DRKR_dUiPBC/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DRXVpcdAX9A/', category: 'Wardrobe & Storage' },
  { url: 'https://www.instagram.com/p/DQ8-NFdgc6g/', category: 'Wardrobe & Storage' },
  { url: 'https://www.instagram.com/p/DQUeYFyiJyJ/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DPOp-slgVrd/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DPod0WZgT1h/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DOq279hiEME/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DRhmT4ICK2C/', category: 'Office & Commercial' },
  { url: 'https://www.instagram.com/p/DPwUhiRAb8x/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DO6IeLzgZxE/', category: 'Wardrobe & Storage' },
  { url: 'https://www.instagram.com/p/DOtT-fJCJJT/', category: 'Kitchen' },
  { url: 'https://www.instagram.com/p/DRxF4U6iG_a/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DPeY1BLAcaP/', category: 'Wardrobe & Storage' },
  { url: 'https://www.instagram.com/p/DQwfyMsCHOg/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DPWYbUPiMTG/', category: 'Office & Commercial' },
  { url: 'https://www.instagram.com/p/DP6geKUAdA1/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DOxcBkbCFLn/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DOYg-mJAV5J/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DPHAd7wAZQQ/', category: 'Kitchen' },
  { url: 'https://www.instagram.com/p/DOiGbcsCNMW/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DN2PZI20O8B/', category: 'Festive & Occasions' },
  { url: 'https://www.instagram.com/p/DOOJM9EgQzu/', category: 'Kitchen' },
  { url: 'https://www.instagram.com/p/DNXm33HIYx5/', category: 'Office & Commercial' },
  { url: 'https://www.instagram.com/p/DNdYtkPoQtK/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DEPSGYQPhAP/', category: 'Wardrobe & Storage' },
  { url: 'https://www.instagram.com/p/DOGtO1DCApM/', category: 'Bedroom' },
  { url: 'https://www.instagram.com/p/DN-2SVuiL2G/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DN5ykztgUqP/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DOWBAr3COQy/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DNusbbg0CfH/', category: 'Studio & Behind the Scenes' },
  { url: 'https://www.instagram.com/p/DPDlO4TiCBr/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DAvSeYVPGuW/', category: 'Kitchen' },
  { url: 'https://www.instagram.com/p/DB0yODyvoue/', category: 'Home Bar' },
  { url: 'https://www.instagram.com/p/DD6rinxP_38/', category: 'Wardrobe & Storage' },
  { url: 'https://www.instagram.com/p/DDy87PHPGy1/', category: 'Wardrobe & Storage' },
  { url: 'https://www.instagram.com/p/DAdOs8GPgtV/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/DBLlOwBvrEY/', category: 'Kitchen' },
  { url: 'https://www.instagram.com/p/DCBuf2uP3_V/', category: 'Wardrobe & Storage' },
  { url: 'https://www.instagram.com/p/DA3LM1WS_Hl/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/C_fLisvvDLg/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DBqgIvePqYU/', category: 'Wardrobe & Storage' },
  { url: 'https://www.instagram.com/p/DDhB6WDT3_F/', category: 'Wardrobe & Storage' },
  { url: 'https://www.instagram.com/p/DBvn0zWPABi/', category: 'Kitchen' },
  { url: 'https://www.instagram.com/p/DAYEXcCP7sR/', category: 'Kitchen' },
  { url: 'https://www.instagram.com/p/C_xvx5JSP31/', category: 'Kitchen' },
  { url: 'https://www.instagram.com/p/C_fLgW-vRrs/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/C_fLcmWPMCa/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DApvuTRvKpW/', category: 'Kitchen' },
  { url: 'https://www.instagram.com/p/C_dLZcbvcvO/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DNqMKy1oyUd/', category: 'Office & Commercial' },
  { url: 'https://www.instagram.com/p/DAiX5OWSN8q/', category: 'Kitchen' },
  { url: 'https://www.instagram.com/p/DBBLlHqvd0w/', category: 'Wardrobe & Storage' },
  { url: 'https://www.instagram.com/p/C_ppwqBPEhA/', category: 'Kitchen' },
  { url: 'https://www.instagram.com/p/DDomHDUvOtL/', category: 'Kitchen' },
  { url: 'https://www.instagram.com/p/DAQlYHXvigN/', category: 'Design Tips' },
  { url: 'https://www.instagram.com/p/C_dLFbqvFHE/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/C_dLWMoPWG2/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/C_dLSkbv09c/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/C_dLJdfv8V4/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/C_iUyY7PRvN/', category: 'Kitchen' },
  { url: 'https://www.instagram.com/p/C_dK06ovZ-y/', category: 'Residential Interiors' },
  { url: 'https://www.instagram.com/p/DNU29XIIxmk/', category: 'Office & Commercial' },
  { url: 'https://www.instagram.com/p/DQJsy3yE2SF/', category: 'Studio & Behind the Scenes' },
];
